apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    field.cattle.io/creatorId: u-m5cqrsybhq
  labels:
    cattle.io/creator: norman
  managedFields:
  - apiVersion: batch/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:active: {}
        f:startTime: {}
    manager: kube-controller-manager
    operation: Update
  - apiVersion: batch/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:field.cattle.io/creatorId: {}
        f:labels:
          .: {}
          f:cattle.io/creator: {}
      f:spec:
        f:backoffLimit: {}
        f:completions: {}
        f:parallelism: {}
        f:template:
          f:metadata:
            f:annotations:
              .: {}
              f:cattle.io/timestamp: {}
          f:spec:
            f:affinity:
              .: {}
              f:nodeAffinity:
                .: {}
                f:requiredDuringSchedulingIgnoredDuringExecution:
                  .: {}
                  f:nodeSelectorTerms: {}
            f:containers:
              k:{"name":"unit-test-1"}:
                .: {}
                f:args: {}
                f:command: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:resources:
                  .: {}
                  f:limits:
                    .: {}
                    f:cpu: {}
                    f:memory: {}
                    f:sensetime.com/vcuda-core: {}
                    f:sensetime.com/vcuda-memory: {}
                  f:requests:
                    .: {}
                    f:cpu: {}
                    f:memory: {}
                    f:sensetime.com/vcuda-core: {}
                    f:sensetime.com/vcuda-memory: {}
                f:securityContext:
                  .: {}
                  f:allowPrivilegeEscalation: {}
                  f:capabilities: {}
                  f:privileged: {}
                  f:readOnlyRootFilesystem: {}
                  f:runAsNonRoot: {}
                f:stdin: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
                f:tty: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
    manager: rancher
    operation: Update
  name: unit-test-1
  namespace: openmmlab-test
  selfLink: /apis/batch/v1/namespaces/openmmlab-test/jobs/unit-test-1
spec:
  backoffLimit: 0 
  completions: 1
  parallelism: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        job-name: unit-test-1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: diamond.sensetime.com/gpu-model
                operator: In
                values:
                - tesla-t4
      tolerations:
      - key: diamond.sensetime.com/node-region
        operator: "Equal"
        value: "gpu-t4"
        effect: "NoExecute"
      containers:
      - args:
        - c
        - python
        - -m
        - pip
        - install
        - -r
        - requirements/test.txt
        command:
        - sh
        image: registry.sensetime.com/mmcv/ubuntu_1804_py_37_cuda_101_cudnn_7_torch_160_dev:20211020
        imagePullPolicy: Always
        name: mmcv-unit-test
        resources:
          limits:
            cpu: 4000m
            memory: 8192Mi
            sensetime.com/vcuda-core: "100"
            sensetime.com/vcuda-memory: "32"
          requests:
            cpu: 250m
            memory: 256Mi
            sensetime.com/vcuda-core: "50"
            sensetime.com/vcuda-memory: "16"
        volumeMounts:
          - mountPath: /dev/shm
            name: cache-volume
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      volumes:
      - emptyDir:
          medium: Memory
          sizeLimit: 8Gi
        name: cache-volume
      imagePullSecrets:
        - name: registry-secret
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  active: 1
