test_demo:
  # 2d_animal_demo.md
  2d_animal_demo:
    checkpoints:
      - url: 
      - url: 
      - url: https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_2x_coco/faster_rcnn_r50_fpn_2x_coco_bbox_mAP-0.384_20200504_210434-a5d8aa15.pth

  # 2d_face_demo.md
  2d_face_demo:
    videos:
      - url: https://user-images.githubusercontent.com/87690686/137441355-ec4da09c-3a8f-421b-bee9-b8b26f8c2dd0.mp4

  # 2d_hand_demo.md
  2d_hand_demo:
    checkpoints:
      - url: https://download.openmmlab.com/mmpose/mmdet_pretrained/cascade_rcnn_x101_64x4d_fpn_20e_onehand10k-dac19597_20201030.pth
    videos:
      - url: https://user-images.githubusercontent.com/87690686/137441388-3ea93d26-5445-4184-829e-bf7011def9e4.mp4

  # 2d_human_pose_demo.md
  2d_human_pose_demo:
    checkpoints:
      - url: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth

  # 2d_pose_tracking_demo.md
  2d_pose_tracking_demo:
    checkpoints:
      - url: https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth  # mmdet

  # 2d_wholebody_pose_demo.md
  2d_wholebody_pose_demo:
    checkpoints:
      - url: https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth  # mmdet
    videos:
      - url: https://user-images.githubusercontent.com/87690686/137440639-fb08603d-9a35-474e-b65f-46b5c06b68d6.mp4

  # 3d_human_pose_demo.md
  3d_human_pose_demo:
    checkpoints:
      - url: https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth


